<?xml version="1.0"?>
<package format="2">
  <name>linux_performance</name>
  <version>0.0.0</version>
  <description>ROS1-accessible Linux CPU performance tuning helper scripts.</description>

  <maintainer email="lxk@todo.todo">lxk</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <export>
  </export>
</package>
